### ISSUE TITLE
Implement a CI/CD pipeline

### ISSUE THREAD

**Issue by senart** [scalefocus/virusafe-android#1]
**Is your feature request related to a problem? Please describe.**
Currently there is no active CI/CD enabled for this project. This makes it hard to review PRs as it requires manual building and testing of the app.

**Describe the solution you'd like**
Implement a CI/CD pipeline, possibly use [buddybuild](https://www.buddybuild.com) or [Travis CI](https://travis-ci.org). You can refer to the way Mozilla have setup the pipelines for their [iOS](https://github.com/mozilla-mobile/firefox-ios) and [Android](https://github.com/mozilla-mobile/focus-android) projects.

**Describe alternatives you've considered**
Maybe use another build automation platform, like Circle CI and etc.

**Additional context**
N/A

**Comment by dtopuzov** [comment]
[GitHub Actions ](https://github.com/features/actions) is free for open source and work well.
