### ISSUE TITLE
NOTICE file and license headers missing at each source code file

### ISSUE THREAD

**Issue by borisstoyanov** [scalefocus/virusafe-android#6]
**Describe the bug**
It seems that this contribution does not follow 'The Apache Way' of applying an ACS 2.0 license. Please have a read here: https://www.apache.org/legal/src-headers.html#notice

It is expected to have a NOTICE file at the root level as described in the instructions and each source code file should have a license header in order to implement the 2.0 license. 

**Expected behavior**
As above 

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by senart** [comment]
Thank you for getting involved!

Isn't this required only for Apache committers and PMC members, as stated in their [Overview section](https://www.apache.org/legal/src-headers.html#purpose) about source headers?
```
This document describes how Apache committers and PMC members should handle source file licensing and copyright notices.
It does not apply to developers outside the ASF who are applying the Apache License to their work...
```

**Comment by borisstoyanov** [comment]
Yes, you seems to be right, as this project does not fall into 'Community Led Development' does not apply. Closing this one.
